### PR TITLE
Added prismarine shard

### PR DESCRIPTION
**Pull request by codetaylor**

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
I should really change those propertyInts so that its related to the length of that item array, this would make that much faster.  Lemme finish reviewing this then it'll probably be merged

**Comment by codetaylor** [comment]
It looks like I totally wrecked the formatting in the third commit. It's such a habit to hit the hotkey for formatting I didn't even realize I did it until I looked at the commit...

**Comment by Shadows-of-Fire** [comment]
As far as that xp code goes, it was legacy from the old config file that has yet to be returned, I personally wasn't going to implement it back so it can stand to be removed.

**Comment by Shadows-of-Fire** [comment]
I'm not horribly particular about caring for what the formatting looks like @p455w0rd might be though...

**Pull request merged**
